CREATE TABLE ChatDialog (
  dialog_id VARCHAR(128) NOT NULL PRIMARY KEY,
  user_1 VARCHAR(128) NOT NULL,
  user_2 VARCHAR(128) NOT NULL,
  user_1_read_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  user_2_read_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  FOREIGN KEY (user_1) REFERENCES User(uid),
  FOREIGN KEY (user_2) REFERENCES User(uid)
);

CREATE TABLE ChatMessage (
  f_dialog_id VARCHAR(128) NOT NULL,
  message_id VARCHAR(128) NOT NULL PRIMARY KEY,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  content VARCHAR(4096) NOT NULL,

  FOREIGN KEY (f_dialog_id) REFERENCES ChatDialog(dialog_id)
);
